"""Offline training for the L5 physics-informed digital twin.

    python training/train_twin.py --out var/twin/highway.pt

What "training the twin" actually means here
----------------------------------------------
The twin answers: *given the state the vehicle is in, what command does the
modelled physics expect next?* So a training example is a state paired with the
command that physically explains the motion observed in that state.

That labelling does not require a trained controller, which matters because L4's
policy does not exist yet. For a vehicle experiencing lateral acceleration
``a_lat``, the command that explains it is the one whose implied acceleration
matches: ``B . pi = a_lat``, inverted through the platform's configured control
effectiveness. The corpus is therefore self-labelling from kinematics alone.

This is also why the twin cannot simply be fitted to whatever Core-A eventually
does. A twin trained to imitate the proposer would drive every non-conformity
score to zero and disarm the statistical gate while every dashboard reported
health. It is trained against physics precisely so that the proposer cannot move
it.

What this corpus is, and is not
--------------------------------
It is generated by a kinematic bicycle model -- the same family of motion the UKF
already assumes. Two consequences, both of which must travel with any number
produced from a twin trained on it:

* It **can** expose an implementation error in the twin: wrong feature order,
  broken physics residual, a network that failed to converge.
* It **cannot** expose a modelling error, because the model generating the data
  and the model being learned agree by construction.

That is the same limitation recorded as technical debt item 1 for the UKF's
synthetic validation, and it is not fixed by training harder. It is fixed by
CARLA. Until then, a twin trained here is a working twin on simulated dynamics
and must be labelled as such wherever its outputs are reported.

Why the checkpoint digest is printed
--------------------------------------
A verdict is traceable only if a reader can tell which twin produced the
prediction underneath it. The digest is the model's counterpart to the
configuration hash, and it belongs in the run record beside it.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import random
from pathlib import Path

import torch

from astra.layers.l5_twin.network import (
    FEATURE_DIMENSION,
    TwinNetwork,
    physics_residual,
    state_features,
)

# The development actuation space is (throttle, brake, steer); only steering
# produces lateral acceleration. Stated here rather than imported from config
# because this script trains a twin *for* a platform and must be told which.
CONTROL_EFFECTIVENESS = (0.0, 0.0, 120.0)
STEERING_CHANNEL = 2

FAST_STATE_SPEED_INDEX = 2
FAST_STATE_HEADING_INDEX = 3
FAST_STATE_LATERAL_INDEX = 4


def generate_corpus(
    *, samples: int, seed: int
) -> tuple[list[tuple[float, ...]], list[tuple[float, ...]]]:
    """Generate a self-labelling kinematic corpus.

    Sweeps speed, heading and lateral acceleration over the ranges a highway
    manoeuvre covers, and labels each state with the command whose implied
    lateral acceleration equals the observed one.

    Args:
        samples: How many examples to generate.
        seed: Seed for the sampler, so a corpus is reproducible.

    Returns:
        ``(features, commands)`` -- feature rows and their target commands.
    """
    rng = random.Random(seed)
    gain = CONTROL_EFFECTIVENESS[STEERING_CHANNEL]
    features: list[tuple[float, ...]] = []
    commands: list[tuple[float, ...]] = []

    for _ in range(samples):
        speed = rng.uniform(5.0, 35.0)
        heading = rng.uniform(-math.pi, math.pi)
        # Bounded by roughly what dry tarmac supports, so the corpus does not
        # teach the twin to expect physically unavailable manoeuvres.
        lateral = rng.uniform(-6.0, 6.0)
        state_mean = (0.0, 0.0, speed, heading, lateral)

        features.append(
            state_features(
                state_mean,
                speed_index=FAST_STATE_SPEED_INDEX,
                heading_index=FAST_STATE_HEADING_INDEX,
                lateral_index=FAST_STATE_LATERAL_INDEX,
            )
        )
        steer = lateral / gain
        command = [0.0] * len(CONTROL_EFFECTIVENESS)
        command[STEERING_CHANNEL] = steer
        commands.append(tuple(command))

    return features, commands


def train(
    *,
    features: list[tuple[float, ...]],
    commands: list[tuple[float, ...]],
    hidden_width: int,
    physics_weight: float,
    epochs: int,
    learning_rate: float,
    seed: int,
) -> tuple[TwinNetwork, float, float]:
    """Fit the twin against data and physics.

    Args:
        features: Feature rows.
        commands: Target commands.
        hidden_width: Hidden layer width.
        physics_weight: Weight on the physics residual.
        epochs: Full passes over the corpus.
        learning_rate: Adam step size.
        seed: Seed for weight initialisation, so a run is reproducible.

    Returns:
        ``(network, final_data_loss, final_physics_loss)``.
    """
    torch.manual_seed(seed)
    network = TwinNetwork(hidden_width=hidden_width, command_dimension=len(CONTROL_EFFECTIVENESS))
    optimiser = torch.optim.Adam(network.parameters(), lr=learning_rate)

    x = torch.tensor(features, dtype=torch.float32)
    y = torch.tensor(commands, dtype=torch.float32)
    lateral = x[:, -1]
    effectiveness = torch.tensor(CONTROL_EFFECTIVENESS, dtype=torch.float32)

    data_loss = torch.zeros(())
    phys_loss = torch.zeros(())
    network.train()
    for epoch in range(epochs):
        optimiser.zero_grad()
        predicted = network(x)
        data_loss = torch.mean((predicted - y) ** 2)
        phys_loss = physics_residual(predicted, lateral, effectiveness)
        (data_loss + physics_weight * phys_loss).backward()
        torch.nn.utils.clip_grad_norm_(network.parameters(), 1.0)
        optimiser.step()
        if epoch % max(1, epochs // 10) == 0:
            print(
                f"  epoch {epoch:5d}  data {data_loss.detach().item():.6e}  "
                f"physics {phys_loss.detach().item():.6e}"
            )

    # Fit one head, then give every context the same starting point. Without
    # this the other heads keep their random initialisation and the twin
    # predicts noise everywhere but UNCLASSIFIED -- see
    # `TwinNetwork.seed_heads_from`.
    network.seed_heads_from()
    network.eval()
    return network, data_loss.detach().item(), phys_loss.detach().item()


def main() -> int:
    """Generate a corpus, train the twin and write a checkpoint.

    Returns:
        A process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("var/twin/synthetic.pt"))
    parser.add_argument("--samples", type=int, default=4000)
    parser.add_argument("--epochs", type=int, default=3000)
    parser.add_argument("--hidden-width", type=int, default=32)
    parser.add_argument("--physics-weight", type=float, default=1.0)
    parser.add_argument("--learning-rate", type=float, default=1e-2)
    parser.add_argument("--seed", type=int, default=20260730)
    args = parser.parse_args()

    print("ASTRA -- L5 digital twin, offline training")
    print("  corpus: synthetic kinematic bicycle. NOT real vehicle physics.")
    print("  a twin trained here can expose an implementation error, never a")
    print("  modelling one, because the generating and learned models agree.")
    print()

    features, commands = generate_corpus(samples=args.samples, seed=args.seed)
    print(f"corpus: {len(features)} examples, {FEATURE_DIMENSION} features each")

    network, data_loss, phys_loss = train(
        features=features,
        commands=commands,
        hidden_width=args.hidden_width,
        physics_weight=args.physics_weight,
        epochs=args.epochs,
        learning_rate=args.learning_rate,
        seed=args.seed,
    )

    print()
    print(f"final data loss    : {data_loss:.6e}")
    print(f"final physics loss : {phys_loss:.6e}")

    # Held-out check on a corpus the network never saw.
    holdout_features, holdout_commands = generate_corpus(samples=1000, seed=args.seed + 1)
    with torch.no_grad():
        predicted = network(torch.tensor(holdout_features, dtype=torch.float32))
        target = torch.tensor(holdout_commands, dtype=torch.float32)
        rmse = float(torch.sqrt(torch.mean((predicted - target) ** 2)))
    print(f"held-out RMSE      : {rmse:.6e}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    torch.save(network.state_dict(), args.out)

    digest = hashlib.sha256()
    for name, parameter in sorted(network.state_dict().items()):
        digest.update(name.encode("utf-8"))
        digest.update(parameter.detach().cpu().numpy().tobytes())

    print()
    print(f"checkpoint         : {args.out}")
    print(f"weights digest     : {digest.hexdigest()[:16]}")
    print()
    print("Record the digest beside the configuration hash in the run report:")
    print("it is what makes a verdict traceable to the model underneath it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
